# DAOS agent configuration file.
#
# Location of this configuration file is determined by first checking for the
# path specified through the -f option of the daos_agent command line.
# Otherwise, /etc/daos.conf is used.

# Section describing the client configuration

# Although not supported for now, one might want to connect to multiple
# DAOS installations from the same node in the future.

# Specify the associated DAOS systems.
# Name must match name specifed in the daos_server.conf file on the server.
#
systems:
-
  name: daos

  # Management service replicas.
  # Hosts can be specified with or without port, default port below
  # assumed if not specified.
  # default: hostname of this node at port 10000 for local testing
  #
  # msrep: ['hostname1:10001','hostname2:10001','hostname3:10001']
  # msrep: [hostname1,hostname2,hostname3]

  # Force a different port number to connect to on daos_server
  # (distinct from management service replica port assignments).
  # default: 10000
  #
  # port: 10000

  # Path to CA certificate
  # not required if the DAOS server is configured in an insecured way
  #
  # cacert: ./.daos/ca.crt

  # path to client certificate and key file.
  # discarded if no CA certificate is passed.
  # default: ./.daos/daos.{crt,key}
  #
  # cert: ./.daos/daos.crt
  # key: ./.daos/daos.key
