# DAOS agent configuration file.
#
# Location of this configuration file is determined by first checking for the
# path specified through the -f option of the daos_agent command line.
# Otherwise, /etc/daos.conf is used.
#
# Section describing the client configuration
#
# Although not supported for now, one might want to connect to multiple
# DAOS installations from the same node in the future.
#
# Specify the associated DAOS systems.
# Name must match name specifed in the daos_server.conf file on the server.
#
systems:
-
  name: daos
#
#  # Access points
#  # To operate, DAOS will need a quorum of access point nodes to be available.
#  # Hosts can be specified with or without port, default port below.
#  #
#  # access_pts: ['hostname1:10001','hostname2:10001','hostname3:10001']
#  # access_pts: [hostname1,hostname2,hostname3]
#
#  # Force default port number to connect to on daos_server, this will also
#  # be used when connecting to access points if no port is specified.
#  #
#  # default: 10000
#  # port: 10001
#
#  # Path to CA certificate
#  # Not required if the DAOS server is configured in an insecured way
#  #
#  # ca_cert: ./.daos/ca.crt
#
#  # Path to client certificate and key file.
#  # Discarded if no CA certificate is passed.
#  #
#  # default: ./.daos/daos.{crt,key}
#  # cert: ./.daos/daos.crt
#  # key: ./.daos/daos.key
