# DAOS server configuration file.
#
# Location of this configuration file is determined by first checking for the
# path specified through the -f option of the daos_server command line.
# Otherwise, /etc/daos_server.conf is used.

# Name associated with the DAOS system.
# Immutable after reformat.
#
name: daos

# Management service replicas.
# To operate, DAOS will need a quorum of those nodes to be available.
# Immutable after reformat.
# Hosts can be specified with or without port, default port below
# assumed if not specified.
# default: hostname of this node at port 10000 for local testing
#
# msrep: ['hostname1:10001','hostname2:10001','hostname3:10001']
# msrep: [hostname1,hostname2,hostname3]

# Force a different port number to bind daos_server to
# (distinct from management service replica port assignments).
# default: 10000
#
# port: 10000

# path to CA certificate.
# If not specified, DAOS will start in insecure way which means that
# anybody can administrate the DAOS installation and access data
#
# cacert: ./.daos/ca.crt

# Path to server certificate and key file.
# discarded if no CA certificate is passed.
# default: ./.daos/daos_server.{crt,key}
#
# cert: ./.daos/daos_server.crt
# key: ./.daos/daos_server.key

# Fault domain path
# Immutable after reformat.
# default: /hostname for a local configuration w/o fault domain
#
# fault_path: /vcdu0/rack1/hostname

# Fault domain callback
# Path to executable which will return fault domain string.
# Immutable after reformat.
#
# fault_callback: ./.daos/fd_callback

# Use specific OFI interfaces.
# Specify either a single interface that will be used by all the
# intances or a comma-seperated list of interfaces, one per instance.
# By default, the DAOS server will auto-detect and use all fabric
# interfaces if any and fall back to socket on the first eth card
# otherwise.
#
# interfaces: [qib0,qib1]

# Use specific OFI provider.
# Force a specific provider to be used by all the servers.
# The default provider depends on the interfaces that will be auto-detected:
# ofi+psm2 for Omni-Path, ofi+verbs;ofi_rxm for Infiniband/RoCE and finally
# ofi+socket for non-RDMA-capable Ethernet.
#
# provider: ofi+verbs;ofi_rxm

# If no pre-configured mountpoins are specified, DAOS will auto-detect
# NVDIMMs, configure them in interleave mode, format with ext4 and
# mount with the DAX extension. This option allows to specify a
# preferred path where the mountpoints will be created.
# default: /mnt/daos
#
# mount_path: /mnt/daos

# NVMe SSD whitelist. Only use NVMe controllers with specific PCI addresses.
# Immutable after reformat, colons replaced by dots in PCI identifiers.
# By default, DAOS will use all the NVMe-capable SSDs that don't have active
# mount points.
#
# nvme_include: [pcie1000.0.0.0.1,pcie1000.0.0.0.2,pcie1000.0.0.0.3]

# NVMe SSD blacklist. Only use NVMe controllers with specific PCI addresses.
# Overrides drives listed in nvme_include and forces auto-detection to skip
# those those drives.
# Immutable after reformat, colons replaced by dots in PCI identifiers.
#
# nmve_exclude: [pcie1000.0.0.0.1]

# When Hyperthreading is enabled and supported on the system, this parameter
# defines whether the DAOS service thread should only be bound to different
# physical cores (value 0) or hyperthreads (value 1).
# default: 0
#
# hyperthreading: 1

# When per-server definitions exist, auto-configuration is not performed.
# Without, node resources will automatically be assigned to server instances
# one per socket.
servers:
#-
#  name: server1
#
#  # Logical CPU assignments as identified in /proc/cpuinfo
#  # e.g. [0-24] for CPU 0 to 24.
#  # Immutable after reformat.
#  #
#  cpus: [0-20]
#
#  # Use specific OFI interfaces.
#  # Specify the network interface that will be used by this server.
#  #
#  interface: qib0
#
#  # Force a pre-configured mountpoint to be used by this server.
#  # Path should be unique to server instance (an use different subdirs).
#  #
#  mount_force: /mnt/daos/1
#
#  # NVMe SSD list. Force specific SSDs to be used by this server instance.
#  # List of unique NVMe IDs, should be different across different server
#  # instances.
#  # Immutable after reformat, colons replaced by dots in PCI identifiers.
#  #
#  nvme_force: [pcie1000.0.0.0.1]
#
#  # Force specific debug mask (D_LOG_MASK) at start up time.
#  # By default, just use the default debug mask used by DAOS.
#  debug_masl: WARN
#-
#  name: server2
#  # Logical CPU assignments as identified in /proc/cpuinfo
#  # e.g. [0-24] for CPU 0 to 24.
#  # Immutable after reformat.
#  #
#  cpus: [21-40]
#
#  # Use specific OFI interfaces.
#  # Specify the network interface that will be used by this server.
#  #
#  interface: qib1
#
#  # Force a pre-configured mountpoint to be used by this server.
#  # Path should be unique to server instance (an use different subdirs).
#  #
#  mount_force: /mnt/daos/2
#
#  # NVMe SSD list. Force specific SSDs to be used by this server instance.
#  # List of unique NVMe IDs, should be different across different server
#  # instances.
#  # Immutable after reformat, colons replaced by dots in PCI identifiers.
#  #
#  nvme_force: [pcie1000.0.0.0.2]
#
#  # Force specific debug mask (D_LOG_MASK) at start up time.
#  # By default, just use the default debug mask used by DAOS.
#  debug_masl: WARN
